### ISSUE TITLE
Evaluate the possiblity to drop DataAdaptor

### ISSUE THREAD

**Issue by gabesullice** [e0ipso/shaper#7]
I don't understand the remaining distinction between a transformation, reversible transformation and data adapter.

It seems like the DataAdaptor name could go away and just be a ReversibleTransformationBase that extends from TransformationBase

**Comment by e0ipso** [comment]
That's not correct. The validation is different at this point since we need to enforce common validation in the _internal_ shape.

**Comment by gabesullice** [comment]
I'm not saying the behavior needs to be dropped, I'm just saying to move the ReversibleTransformation

**Comment by gabesullice** [comment]
Ugh, I'm sorry for all the noise. I'm clicking buttons on accident.

**Comment by e0ipso** [comment]
@gabesullice I'm not 💯 sure I'm following your suggestion. Can you clarify a bit? Maybe a quick PR would be the simplest.

**Comment by e0ipso** [comment]
I am gardening the issue queue a bit. If you still want this, let me know.
