### ISSUE TITLE
Extend ReversibleTransformationInterface from TransformationInterface

### ISSUE THREAD

**Issue by gabesullice** [e0ipso/shaper#8]
https://github.com/e0ipso/shaper/blob/84ba567cb3217765d3c8f9a820b0450efa6ad7d1/src/DataAdaptor/ReversibleTransformationInterface.php#L7

Right now, a ReversibleTransformationInterface only is one-way since it only has the undo method :P

**Comment by e0ipso** [comment]
Honestly I can go either way. I'll be happy to merge a PR in that sense.

**Comment by e0ipso** [comment]
This seems to have gotten stuck, feel free to request a re-open if you still want this to happen.
