### ISSUE TITLE
Use static::class in this cases, so the message is more correct.

### ISSUE THREAD

**Issue by ndobromirov** [e0ipso/shaper#9]
Once the exception is triggered, it's very confusing, as it points to some base class that has the behavior and not the actual class that does not comply to it's schema...

Maybe add more meta-data for debugging, like the validation errors for example.

https://github.com/e0ipso/shaper/blob/a9b1420201ca3d0831d91879f72bf90e1186fd32/src/Transformation/TransformationTransformerTrait.php#L21

**Comment by e0ipso** [comment]
That's a good point. Would you be sending a PR for this?

**Comment by ndobromirov** [comment]
I could in the next week or so.

**Comment by e0ipso** [comment]
This was fixed.
